Repository tonzo-studios/rogue-like, pull requests merged in 2018-05, with the labels that each got.

#37 Ditch commands and make new Dungeon class
  action_manager.py
  behavior.py
  command.py
  display_manager.py
  dungeon.py
  entities.py
  level.py
  main.py
  misc.py
  requirements.txt
Labels: core

#40 Fix: Only attempt to pick up entities of type item
  action_manager.py
Labels: bug

#36 Add more testing
  .travis.yml
  backpack.py
  display_manager.py
  dungeon.py
  effects.py
  entities.py
  items.json
  misc.py
  registry.py
  tests/test_entities.py
  tests/test_misc.py
  tests/test_vector.py
Labels: testing

#53 Use CSV files to store data
  actors.csv
  actors.json
  items.csv
  items.json
  registry.py
Labels: enhancement
